print("Welcome to the Madlibs Game!")
print("Let's create a fun story together.")
print("Please enter the correct type of words as asked.\n")

name = input("Enter a person's name: ")
noun1 = input("Enter a noun (object or thing): ")
verb1 = input("Enter a verb (action word): ")
noun2 = input("Enter another noun (animal or object): ")
verb2 = input("Enter another verb (action word): ")
adjective1 = input("Enter an adjective (describing word): ")
place = input("Enter a place name: ")
emotion = input("Enter an emotion (happy, sad, angry, etc.): ")
noun3 = input("Enter one more noun (any object): ")

print("\nHere is your Madlibs story:\n")

print(f"Once upon a time, there was a person named {name}.")
print(f"{name} lived in a place called {place}.")
print(f"One day, {name} found a {adjective1} {noun1} and started to {verb1}.")
print(f"Suddenly, a {noun2} appeared and they decided to {verb2} together.")
print(f"{name} was feeling very {emotion}.")
print(f"Later, they discovered a mysterious {noun3}.")
print("After that moment, their life changed forever.")
print("They lived happily ever after.")
